variables:
    PRIVATESUBNET_RTNAME:
        required: false
        description: The private subnet route table
        default: cc-default_vpc-default_private_subnet-rt
    VPC_NAME:
        required: false
        description: The VPC
        default: cc-default_vpc
    PRIVATESUBNET_NAME:
        required: false
        description: The private subnet
        default: cc-default_vpc-default_private_subnet
