## This file was auto-generated by CloudCoreo CLI
## This file was automatically generated using the CloudCoreo CLI
##
## This config.rb file exists to create and maintain services not related to compute.
## for example, a VPC might be maintained using:
##
## coreo_aws_vpc_vpc "my-vpc" do
##   action :sustain
##   cidr "12.0.0.0/16"
##   internet_gateway true
## end
##
coreo_aws_vpc_routetable "${PRIVATESUBNET_RTNAME}" do
   action :create
   vpc "${VPC_NAME}"
   number_of_tables 3
end

coreo_aws_vpc_subnet "${PRIVATESUBNET_NAME}" do
   action :sustain
   number_of_zones 3
   percent_of_vpc_allocated 50
   route_table "${PRIVATESUBNET_RTNAME}"
   vpc "${VPC_NAME}"
end
